### ISSUE TITLE
creating private azure error. need to specify primary or secondary

### ISSUE THREAD

**Issue by wongz0r** [megaport/terraform-provider-megaport#30]
When trying to create an azure VXC with service key, receiving an error that primary or secondary is not specified. From the protal, this is easily selected. 

What field in the resource do I need to specify this? this is not documented or listed in the terraform registry : https://registry.terraform.io/providers/megaport/megaport/latest/docs/resources/megaport_azure_connection

terraform error msg:
Error: Validation failed: Azure: missing primary_subnet or secondary_subnet, Azure: invalid vlan, Validation of b_csp_request failed

**Comment by flackon** [comment]
I managed to replicate the same error. It appears to be related to the peerings type, possibly something changed in the API backend such that it now requires primary_subnet and secondary_subnet to be specified explicitly for private_peer and microsoft_peer. It's something we'll need to update in a future release.

Previously you would create separate VXC Azure connection resources for the primary and secondary connections and it would automatically create the primary connection first and the secondary connection second. This way still looks to be working with private_peer and microsoft_peer both set to false (the default).

**Comment by flackon** [comment]
Peering functionality for Azure VXC's has been improved in the latest release. That error was because it's not possible to auto-generate peerings for Azure when the source is a Port. With the new release you can now create peerings for Azure when the source is a Port by manually supplying the peering values. If you're using an MCR rather than a Port you can either auto-generate the peering values or manually supply them. The Azure resource documentation has been updated with working examples for both Ports and MCR's.
