### ISSUE TITLE
Ability to specify Azure peering vlan

### ISSUE THREAD

**Issue by danielcarterimanage** [megaport/terraform-provider-megaport#6]
Would like to be able to specify the Azure VXC to use the "Configure single Azure Peering VLAN" options that are available within the portal, along with the Azure peering VLAN id to use.

**Comment by steve-exley** [comment]
That's a good suggestion. We're not actively working on the Azure connection options - there are a few. But we'll add this to our future capabilities roadmap.

**Comment by wongz0r** [comment]
There was recently an updated provider that expanded the megaport_azure_connection to support primary and secondary subnets. However, I was disappointed that the "configure single azure peering VLAN" was not addressed. This is pretty critical since the portal offers this option and is a key reason why we are using megaport with Azure expressroutes. Not being able to push via Terraform is a bit annoying. Can we get this addressed sooner than later? i see this issue was open over a year ago now.

**Comment by gopurx** [comment]
Any update on this feature? We are trying to leverage this feature and automate azure expess route deployment end to end

**Comment by mega-alex** [comment]
This is available in the `main` branch and will be released soon.
