### ISSUE TITLE
Provisioning multiple VXC's on the same port

### ISSUE THREAD

**Issue by angryninja48** [megaport/terraform-provider-megaport#8]
Trying to provision multiple hosted vifs into AWS on the same megaport throws an error.

```
Error: Problem talking with network provisioning system, got code 500: 

  on ../modules/megaport-aws-connection/main.tf line 2, in resource "megaport_aws_connection" "hosted_vif":
   2: resource megaport_aws_connection hosted_vif {
```

```
module.megaport_private_vif1.megaport_aws_connection.hosted_vif: Still creating... [10s elapsed]
module.megaport_private_vif2.megaport_aws_connection.hosted_vif: Still creating... [10s elapsed]
2021/04/27 14:08:12 [DEBUG] module.megaport_private_vif1.megaport_aws_connection.hosted_vif: apply errored, but we're indicating that via the Error pointer rather than returning it: Problem talking with network provisioning system, got code 500: 
2021/04/27 14:08:12 [ERROR] eval: *terraform.EvalApplyPost, err: Problem talking with network provisioning system, got code 500: 
2021/04/27 14:08:12 [ERROR] eval: *terraform.EvalSequence, err: Problem talking with network provisioning system, got code 500: 
2021-04-27T14:08:15.133+1000 [DEBUG] plugin.terraform-provider-megaport_v0.1.4: {"level":"debug","time":"2021-04-27T14:08:15+10:00","message":"Waiting for VXC status transition."}
module.megaport_private_vif2.megaport_aws_connection.hosted_vif: Still creating... [20s elapsed]
module.megaport_private_vif2.megaport_aws_connection.hosted_vif: Still creating... [30s elapsed]
```

Doing the exact same using a curl has no issues

**Comment by angryninja48** [comment]
I have a feeling this is a resource lock or something on the API side of things. When I trim parallelism down to 1 it works with no issues (it takes forever though).

**Comment by steve-exley** [comment]
Thanks @angryninja48 , I have added this issue into our sprint scheduling. Do you have a sample template that reproduces the error?

**Comment by angryninja48** [comment]
Here you go: https://gist.github.com/angryninja48/9080cf5f3a44d26e1ee3256a55258e57

**Comment by steve-exley** [comment]
Just letting you know that I have been able to reproduce the issue, thanks for the gist. I have raised it with our API team internally.

**Comment by steve-exley** [comment]
Hi @angryninja48 , we have released some changes to the Megaport API which improve handling of parallel requests and will continue to work on it.

However the issue here is around requests trying to change the same resource. This will always result in the requests being queued. The AWS VXC's are slow to create and it's likely the Megaport API will start timing out if more than a few are requested to the same Port at once because of the queuing and delays that will occur.

This is in effect the same as setting -parrallelism=1, I would suggest keeping the Terraform template to just the VXC's resources to limit the overall slow down caused by this contention.

**Comment by steve-exley** [comment]
Just an update on this issue. I re-tested with the latest deployed API and can now deploy up to 5 VXC's using the same port simultaneously from the same template in 15 minutes. We'll continue to improve what we can in this space.
